### ISSUE TITLE
consider load old_cbbr_submissions to recipes

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-cbbr#5]
archive `old_cbbr_submissions` to recipes, 
under the schema cbbr_submissions

**Comment by baolingz** [comment]
@SPTKL It has been added as cbbr_submissions."2018.12.11" in recipe. but we need to figure out a solution to load `cbbr_submissions.latest` and `cbbr_submissions."2018.12.11" ` together into the building environment without letting the latter one overwrites the first one.

**Comment by SPTKL** [comment]
use pandas to the load the old one then use `to_sql`
